## Recommendations with MovieTweetings: Collaborative Filtering

One of the most popular methods for making recommendations is **collaborative filtering**.  In collaborative filtering, you are using the collaboration of user-item recommendations to assist in making new recommendations.  

There are two main methods of performing collaborative filtering:

1. **Neighborhood-Based Collaborative Filtering**, which is based on the idea that we can either correlate items that are similar to provide recommendations or we can correlate users to one another to provide recommendations.

2. **Model Based Collaborative Filtering**, which is based on the idea that we can use machine learning and other mathematical models to understand the relationships that exist amongst items and users to predict ratings and provide ratings.


In this notebook, you will be working on performing **neighborhood-based collaborative filtering**.  There are two main methods for performing collaborative filtering:

1. **User-based collaborative filtering:** In this type of recommendation, users related to the user you would like to make recommendations for are used to create a recommendation.

2. **Item-based collaborative filtering:** In this type of recommendation, first you need to find the items that are most related to each other item (based on similar ratings).  Then you can use the ratings of an individual on those similar items to understand if a user will like the new item.

In this notebook you will be implementing **user-based collaborative filtering**.  However, it is easy to extend this approach to make recommendations using **item-based collaborative filtering**.  First, let's read in our data and necessary libraries.

**NOTE**: Because of the size of the datasets, some of your code cells here will take a while to execute, so be patient!

In [85]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import csv
import ast
import tests as t
from scipy.sparse import csr_matrix
from scipy.spatial import distance
from IPython.display import HTML


In [2]:
# Read in the datasets
movies = pd.read_csv('data/movies_clean.csv', index_col=0)
reviews = pd.read_csv('data/reviews_clean.csv', index_col=0)

In [3]:
movies.head()

movie_id                                              movie  \
0         8      Edison Kinetoscopic Record of a Sneeze (1894)   
1        10                La sortie des usines Lumière (1895)   
2        12                      The Arrival of a Train (1896)   
3        25  The Oxford and Cambridge University Boat Race ...   
4        91                         Le manoir du diable (1896)   

               genre  date  1800's  1900's  2000's  Documentary  Adventure  \
0  Documentary|Short  1894       1       0       0            1          0   
1  Documentary|Short  1895       1       0       0            1          0   
2  Documentary|Short  1896       1       0       0            1          0   
3                NaN  1895       1       0       0            0          0   
4       Short|Horror  1896       1       0       0            0          0   

   Animation  ...  War  Romance  Musical  Film-Noir  Sport  Mystery  Western  \
0          0  ...    0        0        0          0      0        0        0   
1          0  ...    0        0        0          0      0        0        0   
2          0  ...    0        0        0          0      0        0        0   
3          0  ...    0        0        0          0      0        0        0   
4          0  ...    0        0        0          0      0        0        0   

   Horror  Comedy  Music  
0       0       0      0  
1       0       0      0  
2       0       0      0  
3       0       0      0  
4       1       0      0  

[5 rows x 35 columns]

### Measures of Similarity

When using **neighborhood** based collaborative filtering, it is important to understand how to measure the similarity of users or items to one another.  

There are a number of ways in which we might measure the similarity between two vectors (which might be two users or two items).  In this notebook, we will look specifically at two measures used to compare vectors:

* **Pearson's correlation coefficient**

Pearson's correlation coefficient is a measure of the strength and direction of a linear relationship. The value for this coefficient is a value between -1 and 1 where -1 indicates a strong, negative linear relationship and 1 indicates a strong, positive linear relationship. 

If we have two vectors x and y, we can define the correlation between the vectors as:


$$CORR(x, y) = \frac{\text{COV}(x, y)}{\text{STDEV}(x)\text{ }\text{STDEV}(y)}$$

where 

$$\text{STDEV}(x) = \sqrt{\frac{1}{n-1}\sum_{i=1}^{n}(x_i - \bar{x})^2}$$

and 

$$\text{COV}(x, y) = \frac{1}{n-1}\sum_{i=1}^{n}(x_i - \bar{x})(y_i - \bar{y})$$

where n is the length of the vector, which must be the same for both x and y and $\bar{x}$ is the mean of the observations in the vector.  

We can use the correlation coefficient to indicate how alike two vectors are to one another, where the closer to 1 the coefficient, the more alike the vectors are to one another.  There are some potential downsides to using this metric as a measure of similarity.  You will see some of these throughout this workbook.


* **Euclidean distance**

Euclidean distance is a measure of the straightline distance from one vector to another.  Because this is a measure of distance, larger values are an indication that two vectors are different from one another (which is different than Pearson's correlation coefficient).

Specifically, the euclidean distance between two vectors x and y is measured as:

$$ \text{EUCL}(x, y) = \sqrt{\sum_{i=1}^{n}(x_i - y_i)^2}$$

Different from the correlation coefficient, no scaling is performed in the denominator.  Therefore, you need to make sure all of your data are on the same scale when using this metric.

**Note:** Because measuring similarity is often based on looking at the distance between vectors, it is important in these cases to scale your data or to have all data be in the same scale.  In this case, we will not need to scale data because they are all on a 10 point scale, but it is always something to keep in mind!

------------

### User-Item Matrix

In order to calculate the similarities, it is common to put values in a matrix.  In this matrix, users are identified by each row, and items are represented by columns.  



In the above matrix, you can see that **User 1** and **User 2** both used **Item 1**, and **User 2**, **User 3**, and **User 4** all used **Item 2**.  However, there are also a large number of missing values in the matrix for users who haven't used a particular item.  A matrix with many missing values (like the one above) is considered **sparse**.

Our first goal for this notebook is to create the above matrix with the **reviews** dataset.  However, instead of 1 values in each cell, you should have the actual rating.  

The users will indicate the rows, and the movies will exist across the columns. To create the user-item matrix, we only need the first three columns of the **reviews** dataframe, which you can see by running the cell below.

In [4]:
user_items = reviews[['user_id', 'movie_id', 'rating']]
user_items.head()

user_id  movie_id  rating
0        1    114508       8
1        2    208092       5
2        2    358273       9
3        2  10039344       5
4        2   6751668       9

### Creating the User-Item Matrix

In order to create the user-items matrix (like the one above), I personally started by using a [pivot table](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.pivot_table.html). 

However, I quickly ran into a memory error (a common theme throughout this notebook).  I will help you navigate around many of the errors I had, and achieve useful collaborative filtering results! 

_____

`1.` Create a matrix where the users are the rows, the movies are the columns, and the ratings exist in each cell, or a NaN exists in cells where a user hasn't rated a particular movie. If you get a memory error (like I did), [this link here](https://stackoverflow.com/questions/39648991/pandas-dataframe-pivot-memory-error) might help you!

In [5]:
user_by_movie = user_items.pivot(index='user_id', columns='movie_id', values='rating')

In [6]:
user_by_movie.head()

movie_id  91        417       3863      4101      4210      4395      \
user_id                                                                
1              NaN       NaN       NaN       NaN       NaN       NaN   
2              NaN       NaN       NaN       NaN       NaN       NaN   
3              NaN       NaN       NaN       NaN       NaN       NaN   
4              NaN       NaN       NaN       NaN       NaN       NaN   
5              NaN       NaN       NaN       NaN       NaN       NaN   

movie_id  4413      4546      4972      5074      ...  11358398  11388406  \
user_id                                           ...                       
1              NaN       NaN       NaN       NaN  ...       NaN       NaN   
2              NaN       NaN       NaN       NaN  ...       NaN       NaN   
3              NaN       NaN       NaN       NaN  ...       NaN       NaN   
4              NaN       NaN       NaN       NaN  ...       NaN       NaN   
5              NaN       NaN       NaN       NaN  ...       NaN       NaN   

movie_id  11388580  11390036  11454170  11561866  11642302  11644170  \
user_id                                                                
1              NaN       NaN       NaN       NaN       NaN       NaN   
2              NaN       NaN       NaN       NaN       NaN       NaN   
3              NaN       NaN       NaN       NaN       NaN       NaN   
4              NaN       NaN       NaN       NaN       NaN       NaN   
5              NaN       NaN       NaN       NaN       NaN       NaN   

movie_id  11777040  12131262  
user_id                       
1              NaN       NaN  
2              NaN       NaN  
3              NaN       NaN  
4              NaN       NaN  
5              NaN       NaN  

[5 rows x 13850 columns]

In [7]:
assert reviews.user_id.nunique() == user_by_movie.shape[0], "Oh no! Your matrix should have {} rows, and yours has {}!".format(reviews.user_id.nunique(), user_by_movie.shape[0])
print("Looks like you are all set! Proceed!")
HTML('<img src="images/greatjob.webp">')

Looks like you are all set! Proceed!


`2.` Now that you have a matrix of users by movies, use this matrix to create a dictionary where the key is each user and the value is an array of the movies each user has rated.

In [8]:
np.array(user_by_movie.loc[2].dropna().index)

array([  208092,   358273,  6751668,  7131622,  7975244,  7984734,
        8367814,  8579674,  8946378, 10039344], dtype=int64)

In [9]:
# Create a dictionary with users and corresponding movies seen

def movies_watched(user_id):
    '''
    INPUT:
    user_id - the user_id of an individual as int
    OUTPUT:
    movies - an array of movies the user has watched
    '''
    movies = np.array(user_by_movie.loc[user_id].dropna().index)

    return movies


def create_user_movie_dict():
    '''
    INPUT: None
    OUTPUT: movies_seen - a dictionary where each key is a user_id and the value is an array of movie_ids
    
    Creates the movies_seen dictionary
    '''
    user_ids = np.array(user_by_movie.index)
    movies_seen = {}

    for id in user_ids:
        movies_seen[id] = movies_watched(id)
    
    return movies_seen

movies_seen = create_user_movie_dict()

In [10]:
movies_watched(1)

array([114508], dtype=int64)

`3.` If a user hasn't rated more than 2 movies, we consider these users "too new".  Create a new dictionary that only contains users who have rated more than 2 movies.  This dictionary will be used for all the final steps of this workbook.

In [11]:
# Remove individuals who have watched 2 or fewer movies - don't have enough data to make recs

def create_movies_to_analyze(movies_seen, lower_bound=2):
    '''
    INPUT:  
    movies_seen - a dictionary where each key is a user_id and the value is an array of movie_ids
    lower_bound - (an int) a user must have more movies seen than the lower bound to be added to the movies_to_analyze dictionary

    OUTPUT: 
    movies_to_analyze - a dictionary where each key is a user_id and the value is an array of movie_ids
    
    The movies_seen and movies_to_analyze dictionaries should be the same except that the output dictionary has removed 
    
    '''
    movies_to_analyze = {}

    for key in movies_seen.keys():
        if movies_seen[key].shape[0] > lower_bound:
            movies_to_analyze[key] = movies_seen[key]

    
    return movies_to_analyze

movies_to_analyze = create_movies_to_analyze(movies_seen)

In [12]:
len(movies_to_analyze)

3494

In [13]:
# Run the tests below to check that your movies_to_analyze matches the solution
assert len(movies_to_analyze) == 3494, "Oops!  It doesn't look like your dictionary has the right number of individuals."
assert len(movies_to_analyze[2]) == 10, "Oops!  User 2 didn't match the number of movies we thought they would have."
assert len(movies_to_analyze[7])  == 10, "Oops!  User 7 didn't match the number of movies we thought they would have."
print("If this is all you see, you are good to go!")

If this is all you see, you are good to go!


### Calculating User Similarities

Now that you have set up the **movies_to_analyze** dictionary, it is time to take a closer look at the similarities between users. Below is the pseudocode for how I thought about determining the similarity between users:

```
for user1 in movies_to_analyze
    for user2 in movies_to_analyze
        see how many movies match between the two users
        if more than two movies in common
            pull the overlapping movies
            compute the distance/similarity metric between ratings on the same movies for the two users
            store the users and the distance metric
```

However, this took a very long time to run, and other methods of performing these operations did not fit on the workspace memory!

Therefore, rather than creating a dataframe with all possible pairings of users in our data, your task for this question is to look at a few specific examples of the correlation between ratings given by two users.  For this question consider you want to compute the [correlation](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.corr.html) between users.

`4.` Using the **movies_to_analyze** dictionary and **user_by_movie** dataframe, create a function that computes the correlation between the ratings of similar movies for two users.  Then use your function to compare your results to ours using the tests below.

In [14]:
movies_to_analyze[2]

array([  208092,   358273,  6751668,  7131622,  7975244,  7984734,
        8367814,  8579674,  8946378, 10039344], dtype=int64)

In [15]:
movies_to_analyze[3]

array([ 790636, 1800241, 2278871, 2395417, 3344922], dtype=int64)

In [32]:
np.sum(user_by_movie)

movie_id
91            6.0
417          34.0
3863         10.0
4101         10.0
4210         10.0
            ...  
11561866    104.0
11642302      2.0
11644170      7.0
11777040     20.0
12131262      8.0
Length: 13850, dtype: float64

In [19]:
df_corr = pd.DataFrame(np.corrcoef(user_by_movie))

In [36]:
user_by_movie.T.index

Int64Index([      91,      417,     3863,     4101,     4210,     4395,
                4413,     4546,     4972,     5074,
            ...
            11358398, 11388406, 11388580, 11390036, 11454170, 11561866,
            11642302, 11644170, 11777040, 12131262],
           dtype='int64', name='movie_id', length=13850)

In [44]:
def compute_correlation(user1, user2):
    '''
    INPUT
    user1 - int user_id
    user2 - int user_id
    OUTPUT
    the correlation between the matching ratings between the two users
    '''
    corr = user_by_movie.loc[[user1,user2]].T.corr().iloc[0,1]
        
    return corr #return the correlation

In [45]:
# Test your function against the solution
assert compute_correlation(2,2) == 1.0, "Oops!  The correlation between a user and itself should be 1.0."
assert round(compute_correlation(35,51), 2) == 0.84, "Oops!  The correlation between user 25 and 51 should be about 0.84."
assert np.isnan(compute_correlation(7,8022)), "Oops!  The correlation between user 7 and 8022 should be a NaN."

print("If this is all you see, then it looks like your function passed all of our tests!")

If this is all you see, then it looks like your function passed all of our tests!


### Why the NaN's?

If the function you wrote passed all of the tests, then you have correctly set up your function to calculate the correlation between any two users.  

`5.` But one question is, why are we still obtaining **NaN** values?  As you can see in the code cell above, users 7 and 8022 have a correlation of **NaN**. Why?

Think and write your ideas here about why these NaNs exist, and use the cells below to do some coding to validate your thoughts. You can check other pairs of users and see that there are actually many NaNs in our data. These NaN's ultimately make the correlation coefficient a less than optimal measure of similarity between two users.

```
In the denominator of the correlation coefficient, we calculate the standard deviation for each user's ratings.  The ratings for two users share the same ratings on the matching movies.  Therefore, the standard deviation is 0.  Because a 0 is in the denominator of the correlation coefficient, we end up with a **NaN** correlation coefficient.  Therefore, a different approach is likely better for this particular situation.

In [55]:
user_by_movie.loc[[35,51]].dropna(axis=1)

movie_id  110475   137523   993846   1234721  1392190  1800241  2788710  \
user_id                                                                   
35            6.0      9.0      8.0      7.0      9.0      7.0      9.0   
51            6.0      8.0      8.0      6.0      8.0      7.0      7.0   

movie_id  2802144  3063516  
user_id                     
35           10.0      6.0  
51            8.0      6.0

`6.` Because the correlation coefficient proved to be less than optimal for relating user ratings to one another, we could instead calculate the euclidean distance between the ratings.  I found [this post](https://stackoverflow.com/questions/1401712/how-can-the-euclidean-distance-be-calculated-with-numpy) particularly helpful when I was setting up my function.  This function should be very similar to your previous function.  When you feel confident with your function, test it against our results.

In [84]:
from scipy.spatial import distance

In [114]:
def compute_euclidean_dist(user1, user2):
    '''
    INPUT
    user1 - int user_id
    user2 - int user_id
    OUTPUT
    the euclidean distance between user1 and user2
    '''
    df_cut = user_by_movie.loc[[user1,user2]].drop_duplicates().T.dropna()

    dist = distance.euclidean(df_cut[user1], df_cut[user2])
    
    return dist #return the euclidean distance

In [115]:
# Test your function against the solution
assert compute_euclidean_dist(2,2) == 0.0, "Oops!  The distance between a user and itself should be 0.0."
assert round(compute_euclidean_dist(35,51), 2) == 3.32, "Oops!  The distance between user 2 and 66 should be about 2.24."

print("If this is all you see, then it looks like your function passed all of our tests!")

If this is all you see, then it looks like your function passed all of our tests!


In [116]:
# Don't change the code here
# This loads our solution dataframe with every possible user pairings
df_dists = pd.read_csv('df_dists.csv')
del df_dists['Unnamed: 0']
df_dists.dropna(inplace=True)

FileNotFoundError: [Errno 2] No such file or directory: 'df_dists.csv'